server:
  port: 8881
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'root'
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    enabled: false
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.pms.domain
